const ADD_MATTER = 'ADD_MATTER';
const LOAD_MATTERS = 'LOAD_MATTERS';
const SET_VISIBILITY = 'SET_VISIBILITY';
const SET_CURRENT_USER = 'SET_CURRENT_USER';

export { ADD_MATTER, LOAD_MATTERS, SET_VISIBILITY, SET_CURRENT_USER };
